- requirements/base.txt
> Add pudb==2016.2 dependecy

- .travis.yml
This ensures local docker image is built and used for testing.
cc @danmcp
> Use local docker image for testing

- chris_backend/plugins/serializers.py
While working on #37, I thought I added those fields but I missed them. Thanks @jbernal0019 for catching it. I added them here.
cc @danmcp
> Added gpu fields to serializer

- docker-destroy-chris_dev.sh
- docker-make-chris_dev.sh
Fix docker destroy volume naming and beautify the make script.
> Fix scripts

- docker-make-chris_dev.sh
Add ability to set computeEnv when running make.
> Add computeEnv to makefile

- chris_backend/plugins/services/charm.py
Closes: https://github.com/redhat-university-partnerships/radiology/issues/52
Depends on: https://github.com/FNNDSC/pfioh/pull/36
> Remove encoding option

- chris_backend/plugins/services/charm.py
- docker-destroy-chris_dev.sh
- docker-make-chris_dev.sh
- requirements/base.txt
Mostly cleanup and add new (DICOM) handling plugins.
> Cleanup and new plugins.

- chris_backend/plugins/tests/test_manager.py
- chris_backend/plugins/tests/test_views.py
Based on https://github.com/FNNDSC/ChRIS_ultron_backEnd/commit/349119dcdc4225e5cf90604dfcd138c2a9101f38#commitcomment-31832408
/cc @jbernal0019 @danmcp @rudolphpienaar
> Add tags to be excluded

- docker-make-chris_dev.sh
> Fix some formatting and add additional plugins

- chris_backend/collectionjson/renderers.py
- chris_backend/feeds/serializers.py
- chris_backend/pipelineinstances/serializers.py
- chris_backend/pipelineinstances/views.py
- chris_backend/pipelines/serializers.py
- chris_backend/pipelines/views.py
- chris_backend/plugininstances/serializers.py
- chris_backend/plugininstances/views.py
- chris_backend/plugins/serializers.py
- chris_backend/plugins/tests/test_serializers.py
- chris_backend/plugins/views.py
- chris_backend/uploadedfiles/serializers.py
- chris_backend/uploadedfiles/views.py
- chris_backend/users/serializers.py
- chris_backend/users/views.py
-Pass a dictionary to plugin descriptors validators
> Make use of the new Collection+JSON renderer that standardizes error messages.

- docker-make-chris_dev.sh
Updates to make script for per-plugin spec to remote compute env.
> Update with per-plugin remote compute env spec

- Dockerfile
- README.md
> Update some in-comment help.

- utils/scripts/swiftCtl.sh
Minor update / fix to `swiftCtl.sh`
> Fix broken IP specifier

- chris_backend/uploadedfiles/serializers.py
> Make fname API descriptor available in the uploadedfiles API

- Dockerfile
- Dockerfile_dev
- README.md
Also here:
- Update API calls in the README
> Add DEBIAN_FRONTEND=noninteractive env variable to Docker files

- make.sh
`$?` seems to be referring to the exit code of `cat dc.out | ./boxes.sh`, but I think you meant for it to be checking `docker-compose -f docker-compose_dev.yml exec ...`
> Remember $? as status variable

- docker-deploy.sh
If the aim of `docker-deploy.sh` is to provide a one-off single-machine deployment command, a few post-installation steps (of which have not yet been documented) should be automated.
- pl-dircopy is hard-coded into the UI, upload to store && register in CUBE
- "host" compute environment is hard-coded into pfcon, register "host" compute env
> Auto upload pl-dircopy and create host compute

- make.sh
Missed bug introduced in https://github.com/FNNDSC/ChRIS_ultron_backEnd/pull/223
> Only one directory, not plural

- docker-compose.yml
- docker-compose_dev.yml
This makes it work not only on MAC but also on Linux dev environments
> Change pidfile to /home/localuser/celerybeat.pid

- Dockerfile_dev
- chris_backend/config/settings/local.py
- chris_backend/plugininstances/models.py
- chris_backend/plugininstances/services/manager.py
- decorate.sh
- docker-compose_dev.yml
- make.sh
This attempts to prevent concurrent calls on `output_file_register` and improve general status handling logic.
> Updates with improved job status handling and polling logic

- decorate.sh
- make.sh
- plugin_add.sh
Format some long lines of printf
Clean up and fix some formatting
Remove all old plugin handling and minor formatting updates
> Update some functions

- make.sh
- plugin_add.sh
- postscript.sh
- user_add.sh
Misc updates to various scripts etc.
> Usability tweaks in scripts

- cparse.sh
- make.sh
- plugin_add.sh
- postscript.sh
Highlight most used make instantiation
Fix old extension specification
Update cparse string with new explicit extension spec
> Fix spec and handling of extensions in plugin cparse string

- make.sh
- postscript.sh
More minor updates on cparse parsing.
> Fix more lingering cparse issues and add new postscript plugins

- chris_backend/config/settings/production.py
Similar to https://github.com/FNNDSC/ChRIS_store/pull/29/files
> Settings for reverse proxy

- cparse.sh
grep -P is a GNU-extension and not available on MacOS
> Replace grep -P w/ sed

- docs/source/authentication.rst
```
$ curl http://localhost:8000/api/v1/auth-token/ \
--data '{"username":"chris","password":"chris1234"}' \
-H 'Accept:application/json' \
{"username":["This field is required."],"password":["This field is required."]}
$ curl http://localhost:8000/api/v1/auth-token/ \
--data '{"username":"chris","password":"chris1234"}' \
-H 'Content-Type:application/json' \
{"token":"938032263848be4ef3142cd02c3749f09b5b51f2"}
```
> Change "Accept" to "Content-Type"

- .gitignore
- Dockerfile
- docker-compose.yml
- docker-deploy.sh
https://github.com/FNNDSC/ChRIS_ultron_backEnd/pull/291
> Pin versions of services in docker-compose.yml

- chris_backend/core/celery.py
- chris_backend/feeds/models.py
- chris_backend/pacsfiles/models.py
- chris_backend/pipelines/models.py
- chris_backend/plugininstances/models.py
- chris_backend/plugininstances/views.py
- chris_backend/plugins/models.py
- chris_backend/servicefiles/models.py
- chris_backend/uploadedfiles/models.py
- docker-compose.yml
- docker-compose_dev.yml
Also switch from `django_filters.DateFilter` to `django_filters.IsoDateTimeFilter` for `models.DateTimeField` filters
> Add a dedicated worker for the periodic tasks

- README.md
- docker-compose_dev.yml
- docker-deploy.sh
- make.sh
- unmake.sh
Also add interactive terminal to `chris_dev` service
> Remove local swarm cluster management from the deployment scripts

- .dockerignore
- .gitignore
- README.md
- deploy.sh
- make.sh
- swarm/docker-compose.yml
- unmake.sh
The default STOREBASE folder is now ./CHRIS_REMOTE_FS
> Fix implementation of -S <storeBase> option in shell scripts

- .dockerignore
- deploy.sh
- kubernetes/prod_deployments/kustomization.yaml
- kubernetes/prod_deployments/resources/chris.yaml
- kubernetes/prod_deployments/resources/scheduler.yaml
- kubernetes/prod_deployments/resources/worker-periodic.yaml
- kubernetes/prod_deployments/resources/worker.yaml
- swarm/prod_deployments/docker-compose.yml
Move DJANGO_DB_MIGRATE and DJANGO_COLLECTSTATIC to the environment files
> WIP, Update chris, worker, worker-periodic and scheduler resources

- README.md
- chris_backend/config/urls.py
- chris_backend/feeds/views.py
- chris_backend/plugins/admin.py
- chris_backend/plugins/tests/test_admin.py
- chris_backend/plugins/tests/test_serializers.py
- chris_backend/plugins/views.py
> Add new ChRIS admin API to CUBE

- chris_backend/core/middleware.py
- chris_backend/core/views.py
- chris_backend/feeds/views.py
- chris_backend/pacsfiles/views.py
- chris_backend/pipelineinstances/views.py
- chris_backend/pipelines/views.py
- chris_backend/plugininstances/views.py
- chris_backend/plugins/admin.py
- chris_backend/plugins/views.py
- chris_backend/servicefiles/views.py
- chris_backend/uploadedfiles/views.py
- chris_backend/users/views.py
- Collection+JSON protocol semantics  only includes GET, POST, PUT and DELETE
- Solves #225
> Strictly allow only http requests with the http verbs of the Collection+JSON protocol semantics 

- chris_backend/plugins/admin.py
> Fix server error when searching by plugin name in the ChRIS admin site

- kubernetes/prod/base/resources/pfcon.yaml
- kubernetes/remote.yaml
- swarm/docker-compose_remote.yml
- swarm/prod/docker-compose.yml
`/var/local/storeBase` adheres to the UNIX filesystem hierarchy.
> Change storebase

- chris_backend/plugininstances/services/manager.py
> Fix log overflow

- chris_backend/plugininstances/services/manager.py
Diff from before #375:
https://github.com/fnndsc/ChRIs_ultron_backend/compare/2b6e2e94a2a237d9f04efbf444377d11b50455f8..tail-logs-keep-nonascii
PostgreSQL supports non-ascii characters, so we should keep them and store them as-is in the DB using `json.dumps(..., ensure_ascii=False)`
> Fix truncation conditional length, keep non-ascii chars

- kubernetes/remote.yaml
> added PFCON_USER and PFCON_PASSWORD

- chris_backend/pipelines/models.py
- chris_backend/pipelines/permissions.py
- chris_backend/pipelines/tests/test_views.py
- chris_backend/pipelines/views.py
- chris_backend/plugins/admin.py
- chris_backend/plugins/tests/test_views.py
- chris_backend/plugins/views.py
> Grant unauthenticated users read-only access to plugin metas, plugins and pipelines

- chris_backend/plugininstances/tasks.py
- chris_backend/plugininstances/tests/test_views.py
- chris_backend/plugininstances/utils.py
Implement proper status transitions for ts plugin instances based on the statuses of all their parent plugin instances.
> Implement proper status transitions for ts plugin instances

- docker-compose_dev.yml
> celery beat scheduler keeps restarting #386 solved

- Dockerfile
Closes https://github.com/FNNDSC/ChRIS_ultron_backEnd/issues/318
> Add HEALTHCHECK

- .dockerignore
- .github/workflows/ci.yml
- .gitignore
- README.md
- action.yml
- docker-compose_just.yml
- githubActions/cleanup.js
- githubActions/main.js
- githubActions/setup.js
- justfile
- Adds support for rootless Podman and testing using Podman.
- Adds config for using this repo as a GitHub Action for running CUBE integration tests.
> Podman and GitHub Actions support

- chris_backend/core/views.py
- chris_backend/plugininstances/serializers.py
- requirements/base.txt
Warning: uses unmerged PR to drf-spectacular https://github.com/tfranzel/drf-spectacular/pull/1307
> Fix OpenAPI spec of PluginInstance nullable fields previous, previous_id, workflow

- chris_backend/plugins/apps.py
- chris_backend/plugins/handlers.py
I already backported this patch to version 5 in the [v5 branch](https://github.com/FNNDSC/ChRIS_ultron_backEnd/tree/v5), this PR adds the change to master.
> Allow any CORS on api/v1/plugins/ and api/v1/plugins/metas/

- chris_backend/pipelines/models.py
- chris_backend/plugininstances/models.py
> Add type filter to plugin instances and name_exact filter to pipelines

- chris_backend/core/serializers.py
- chris_backend/plugins/models.py
> Enable empty file uploads and searching plugins by public repo

- chris_backend/filebrowser/serializers.py
- chris_backend/filebrowser/views.py
- chris_backend/pacsfiles/serializers.py
- chris_backend/pacsfiles/views.py
- chris_backend/pipelines/serializers.py
- chris_backend/pipelines/views.py
- chris_backend/plugininstances/serializers.py
- chris_backend/plugininstances/views.py
- chris_backend/plugins/admin.py
- chris_backend/userfiles/serializers.py
- chris_backend/userfiles/views.py
- chris_backend/users/serializers.py
- chris_backend/users/views.py
- chris_backend/workflows/serializers.py
- chris_backend/workflows/views.py
> Make fields read-only in the serializers' constructors

- chris_backend/core/models.py
- chris_backend/feeds/views.py
- chris_backend/filebrowser/services.py
> Improve speed of DB queries related to granting a user permission to accesss folder/files resources

- Dockerfile
- requirements/base.txt
- requirements/local.txt
1. currently there is some unknown issue with ws in granian.
2. uvicorn can also deal with large-file upload.
> change granian to uvicorn
