chris_backend/collectionjson/services.py, chris_backend/feeds/serializers.py, chris_backend/feeds/tests/test_views.py, chris_backend/feeds/views.py, chris_backend/plugins/serializers.py, chris_backend/uploadedfiles/serializers.py, chris_backend/users/serializers.py, docker-destroy-chris_dev.sh
This fix uncaught serializers error that were generating responses with status code 500 (Internal Server Error) instead of the appropriate 400 (Bad Request). To accomplish this a new **collection_serializer_is_valid** helper decorator was added to the collectionjson django app that is then used to decorate serializers' **is_valid** method in the **feeds, plugins, uploadedfiles and users** django apps.
@danmcp @rudolphpienaar @NicolasRannou This should solve the 500 Internal Server Errors that nico was talking about the other day.
=> Give the appropriate collection+json format to errors raised by serializers with corresponding read-write views.

chris_backend/config/settings/local.py, docker-compose.yml, docker-destroy-chris_dev.sh, docker-make-chris_dev.sh, requirements/base.txt, requirements/local.txt
@NicolasRannou @rudolphpienaar @danmcp This adds the Chris store service to the CUBE's compose. 
The service is not a full production service yet. This means that for instance DB migrations are  applied to the Chris store Django server in the CUBE's make file. That shouldn't be the case for a production service.
The required client libraries to communicate with the store are already available in CUBE (requests and collection-json). So everything is ready to start implementing the registration of plugins in CUBE by making http requests to the Chris store API from the manager script.
=> Add Chris Store service to CUBE's compose

chris_backend/plugins/services/charm.py
in JSON payload from charm --> pfcon --> pman.
This adds `selfexec`, `selfpath`, and `execshell` explicitly to the JSON payload in the `target` paragraph and as such eventually gets to `pman`. This provides values to `pman` that previously it had to collect by running the plugin image and parsing the returned JSON representation in the image.
=> Add new key/value to 'target' spec

chris_backend/plugins/services/manager.py, chris_backend/plugins/tests/test_manager.py, docker-make-chris_dev.sh, requirements/base.txt
CUBE is upgraded to use version 0.0.6 of the ChRIS store client which allows for unauthenticated GET requests to fetch a plugin's representation. Therefore the CUBE's manager can now add a new plugin without a ChRIS store's username and password.
=> Enable unauthenticated HTTP requests to the ChRIS store from CUBE to register plugins in CUBE.

docker-destroy-chris_dev.sh
docker-destroy tries to kill non-existent legacy container.
=> Remove legacy storage container.

chris_backend/plugins/tests/test_manager.py, chris_backend/plugins/tests/test_views.py
As of now, I am removing these 2 tests from integration tests because, when we are calling status method, we are actually checking the DB state in the integration there by causing tests to fail.
Following is the method we are using while calling status:
https://github.com/FNNDSC/ChRIS_ultron_backEnd/blob/322658e97653677afce6fdf979af9e807d22bbae/chris_backend/plugins/services/charm.py#L970-#L990
TODO: Create integration tests which replace this DB state.
=> Remove failing integration tests

.travis.yml, chris_backend/check_db_connection.py, docker-entrypoint.sh, docker-make-chris_dev.sh
- Database migrations are no longer applied as a docker-compose command in the make script. They are now automatically applied in the Django server container's entrypoint script. This will facilitate production deployments in the cloud.
- To check if migrations were properly applied during development just inspect the logs for the Django server containers.
=> Add check_db_connection.py script and apply migrations in the entrypoint script.

chris_backend/feeds/models.py, chris_backend/feeds/serializers.py, chris_backend/feeds/tests/test_models.py, chris_backend/feeds/tests/test_serializers.py
Add get_plugin_instances_status_count method to Feed model.
Add started_jobs, finished_jobs, errored_jobs and cancelled_jobs fields to FeedSerializer.
=> Add started_jobs, finished_jobs, errored_jobs and cancelled_jobs API descriptors to feeds' representations.

chris_backend/plugininstances/services/charm.py, requirements/base.txt
Prefix jid with a string. Currently hard-coded in the base class. 
Prefix necessary to increase jid string length for openshift.
=> Add job ID prefix

chris_backend/plugininstances/services/charm.py
WIP test ... by setting the swift base bucket "prepend" path to only the <username> pattern and not <username>/uploads we should be able to ``dircopy --dir`` from locations in both the uploads and feed tree spaces.
=> Set root path in swift to user and not user/uploadswq

chris_backend/plugininstances/services/charm.py
Charm used to prepend paths with chris <username> and ('uploads' where contextually relevant) since fnames returned from the BE did not return the <username> and for uploads did not require an explicit 'upload' string either.
Now charm assumes that fnames are fully expressive.
=> Remove final prepend string spec from charm filename space

docker-compose_dev.yml
This PR is a cherry pick from z-vol branch that is used to make it work on Fedora 31 VM environment enabling SELinux enabled (mode: enforcing) [1] and coming from https://github.com/FNNDSC/ChRIS_ultron_backEnd/issues/215#issuecomment-668718348 .
https://github.com/FNNDSC/ChRIS_ultron_backEnd/wiki/Fedora-32-Support-for-Docker
> I created a branch z-vol to demonstrate how this works.
I wish this PR will be merged to support the platform enabling SELinux (mode: enforcing).
When [Ubuntu enables SELinux](https://wiki.ubuntu.com/SELinux), it possibly needs this patch too. Fedora is enabling it as a default setting.
=> Add :z to docker-compose_dev.yml

README.md, make.sh
Add documents to fix issues that I faced on Fedora 32.
I am running the installation steps on `README.md` on my local machine, Fedora 32.
Here are some suggestions to update it.  The steps are until `./make.sh` part which I am still trying to run.
```
$ *unmake*
bash: unmake.sh: command not found...
```
```
$ *make*
bash: make.sh: command not found...
```
I think `./make.sh` and `./unmake.sh` are better.
```
$ ./make.sh
ERROR: for chris_ultron_backend_queue_1  Cannot start service queue: OCI runtime create failed: this ve
rsion of runc doesn't work on cgroups v2: unknown
```
I am not sure if the places where I added the document is proper.
3.1. When people uses new Linux distribution where the kernel cgroups v2 is available, but cgroups v1 is not available, we need to enable cgroups v1 …
=> Change outdated *make* syntax

chris_backend/plugininstances/serializers.py, chris_backend/plugininstances/services/manager.py, chris_backend/plugininstances/tests/test_manager.py, chris_backend/plugininstances/tests/test_serializers.py, chris_backend/plugininstances/tests/test_views.py, chris_backend/users/serializers.py, chris_backend/users/tests/test_serializers.py, chris_backend/users/tests/test_views.py, make.sh
- Stronger validation of parameters of type 'path' and 'unextpath' so the plugin instance manager does  not have to deal with invalid dirs
- Faster integration tests
- A welcome to ChRIS `welcome.txt` file is automatically created in the user's personal space when they sign up for a ChRIS account. This allows example API calls in the README to continue to work even with the new stronger validation of parameters
=> Make faster integration tests and stronger validation of parameters of type 'path' and 'unextpath'

chris_backend/core/api.py, chris_backend/core/celery.py, chris_backend/plugininstances/models.py, chris_backend/plugininstances/tasks.py, chris_backend/plugininstances/tests/test_models.py, chris_backend/plugininstances/tests/test_tasks.py, chris_backend/plugininstances/tests/test_views.py, chris_backend/plugininstances/views.py
- Allow a user to run as many plugins as desired as part of a tree of plugin instances without waiting for the ancestor instance to finish
- Introduce a new `waitingForPrevious` plugin instance status
=> Implement on the fly plugin instance tree workflows

chris_backend/plugininstances/tests/test_manager.py, chris_backend/plugininstances/tests/test_views.py, make.sh
- Restart the satellite services after running integration tests to clean their memory
- Fix integration tests to not run the same job id twice
=> Make dev system more stable after running integration tests

decorate.sh, make.sh, plugin_add.sh
```
Sat Oct 13 19:51:34 EDT 2020
```
Without (unnecessarily) having run `locale-gen` to include `en_GB.utf-8` you get many warnings
```
/bin/bash: warning: setlocale: LC_ALL: cannot change locale
```
```
2020-10-13 19:51:34-04:00
```
=> date --rfc-3339=s

make.sh, plugin_add.sh, postscript.sh, user_add.sh
Prune plugins in make.sh
Add intial dev/deploy support
Add script for handling user account creation from bash
Update initial working version
Add choice between CUBE and ChRIS Store
Update title for different contexts
Testing replacement of all user adding by user_add.sh
Fix some display nits
Workflow with external user_add.sh and plugins_add.sh
Add script that registers additional plugins to CUBE
=> Fix minor bug in early print

cparse.sh, make.sh
Update `cparse.sh` to handle `%<extension>` spec in the cparse string.
=> Updates to handle possible extension in plugin core

cparse.sh, make.sh, plugin_add.sh, postscript.sh
- reimplement `cparse.sh` using regex (`grep` and [shell parameter expansion](https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html))
- `*.sh` dev environment suite of tools no longer depends on python! 
- delete `cparse_do` test function
- simplify "cparse" string plugin specification: `[repo/]container[^moc]`
- update all usages of `plugin_add.sh`
- update docs
```bash
$ source cparse.sh
$ cparse fnndsc/pl-pfdicom_tagextract repo container mmn env && echo $repo $container $mmn $env
fnndsc pl-pfdicom_tagextract dcm_tagExtract.py host
$ cparse 'fnndsc/pl-pfdicom_tagextract^moc' repo container mmn env && echo $repo $container $mmn $env
fnndsc pl-pfdicom_tagextract dcm_tagExtract.py moc
$ cparse fnndsc/pl-pfdo_med2img repo container mmn env && echo $repo …
```
=> Cparse using regex and docker inspect

cparse.sh
Didn't know this was a thing before. Better than `jq`, surely better than `grep | sed | cut`
=> Use docker inspect --format

requirements/base.txt
pfurl>=2.3.0.0 deprecates `b_httpResponseBodyParse`, but it turns out this change was ahead of its time. See 
https://github.com/FNNDSC/pfurl/pull/39
The PR was not correct, `pfioh` is not the only service to return malformed HTTP headers -- `pfcon` is guilty as well.
ChRIS_ultron_backEnd's `pfurl>=2.2.2.2` requirement is too permissive
https://github.com/FNNDSC/ChRIS_ultron_backEnd/blob/45b9a29fe8305956ca5bf2aa6d977bae7584ec66/requirements/base.txt#L11
=> Freeze pfurl==2.2.4.6

chris_backend/plugins/services/manager.py
CUBE does not correctly add plugins by URL. In this situation, CUBE is being run with `CHRIS_STORE_URL=http://chrisstore.local:8010/api/v1/`
```
$ docker exec chris python plugins/services/manager.py register --pluginurl https://chrisstore.co/api/v1/plugins/20/ host
Traceback (most recent call last):
File "plugins/services/manager.py", line 366, in <module>
manager.run()
File "plugins/services/manager.py", line 260, in run
self.register_plugin_by_url(options.pluginurl, options.computeresource,
File "plugins/services/manager.py", line 149, in register_plugin_by_url
plg_repr = self.get_plugin_representation_from_store_by_url(url, timeout)
File "plugins/services/manager.py", line 324, in get_plugin_representation_from_store_by_url
plg['parameters'] = …
```
=> Foreign store url

Dockerfile, Dockerfile_dev
Docker image size becomes unreasonably large with large UID because of a longstanding bug in the Go programming language.
https://github.com/moby/moby/issues/5419
Setting `UID=1001` is unsafe because it shadows users which already exist on the host system.
=> Support large arbitrary UID

chris_backend/plugininstances/services/manager.py
- Fixes a bug in which a delete request could be sent from CUBE to pfcon twice for the same job.
=> Add `delete_plugin_instance_job_from_remote` method

chris_backend/config/settings/local.py, chris_backend/plugininstances/services/manager.py, chris_backend/plugininstances/tests/test_tasks.py, chris_backend/plugininstances/views.py
=> Add functionality that deletes a job from the remote compute when the corresponding plugin instance is cancelled or deleted through the REST API

chris_backend/workflows/serializers.py, chris_backend/workflows/tests/test_serializers.py
Elements of `plugin_parameter_defaults` from a POST request to create a workflow is not being validated correctly. This PR fixes the validation, ensuring that for parameters which are mentioned in `plugin_parameter_defaults`, a value for `default` must also be given.
=> Check whether default is given

docker-compose_dev.yml, kubernetes/remote.yaml, make.sh
Fixes #396 
The issue raised which showed 'connection refused' was because the chris_dev remote container and pfcon Kubernetes pod were in different networks. I solved this issue by adding minikube as an external network in the docker-compose file, and the only way communication could be ensured was using minikube's external IP as the HOSTIP. Note: This was only tested with minikube having a docker driver, with other drivers such as hyperkit, the outcome is not ensured.
A second issue after going past this was the error when the job(zip file) was supposed to be submitted from pfcon to pman. These caused tests in the ./make.sh bash script to fail. This issue was fixed by attaching a role and binding the role to the default ServiceAccount in the default Namespace. This issue doesn't exist …
=> Fixed CUBE minikube backend deployment

.gitignore, chris_backend/config/settings/local.py, chris_backend/config/settings/production.py, chris_backend/core/storage/__init__.py, chris_backend/core/storage/helpers.py, chris_backend/core/storage/plain_fs.py, chris_backend/core/storage/storagemanager.py, chris_backend/core/storage/swiftmanager.py, chris_backend/core/swiftmanager.py, chris_backend/feeds/tests/test_views.py, chris_backend/filebrowser/tests/test_views.py, chris_backend/pacsfiles/serializers.py, chris_backend/pacsfiles/tests/test_serializers.py, chris_backend/pacsfiles/tests/test_views.py, chris_backend/pipelines/tests/test_views.py, chris_backend/pipelines/views.py, chris_backend/plugininstances/serializers.py, chris_backend/plugininstances/services/manager.py, chris_backend/plugininstances/tests/test_manager.py, chris_backend/plugininstances/tests/test_serializers.py, chris_backend/plugininstances/tests/test_views.py, chris_backend/servicefiles/serializers.py, chris_backend/servicefiles/tests/test_serializers.py, chris_backend/servicefiles/tests/test_views.py, chris_backend/uploadedfiles/tests/test_views.py, chris_backend/uploadedfiles/views.py, chris_backend/users/serializers.py, chris_backend/users/tests/test_serializers.py, chris_backend/users/tests/test_views.py, docker-compose_noswift.yml
- CUBE is decoupled from Swift
- CUBE can use a filesystem as file storage
Storing files in a directory on the host's filesystem is preferable to object storage in some cases:
- single-machine
- single-replica
- object storage not available
- use NFS for storage
- Minimized `SwiftManager`'s public interface
- Created a new Python package, `core.storage`. `core.swiftmanager` was moved into `core.storage`
- `StorageManager` is an abstract interface implemented by `SwiftManager` 
- Created new `FilesystemManager` implementation of `StorageManager`, which adapts `pathlib` to use a UNIX filesystem as the file storage service for CUBE
- tests were updated to replace `mock.patch.object` usage on `SwiftManager` with a custom context manager `mock_storage` which patches `settings` to use a …
=> Plain filesystem storage

chris_backend/core/apps.py
If the superuser already exists, its password will be set to the value of the `CHRIS_SUPERUSER_PASSWORD` environment variable. This way, the superuser's password can be easily changed by restarting CUBE, and CUBE's state will match the environment variables when the environment variables are changed.
=> Update superuser password if already exists

chris_backend/collectionjson/spectacular_hooks.py, chris_backend/config/settings/common.py
This PR defines a postprocessing hook for drf-spectacular to remove all `vnd.collection+json` media types from the OpenAPI spec.
The `application/vnd.collection+json` media type is inconvenient (and somewhat inefficient) for client code to deal with. It is an obscure spec that isn't used much elsewhere. Most importantly, it causes OpenAPI generated clients to be broken out-of-the-box.
=> Remove all vnd.collection+json content from OpenAPI spec

chris_backend/filebrowser/tests/test_views.py
`filebrowser.tests.test_views.FileBrowserFolderDetailViewTests.test_filebrowserfolder_update_success` would fail if you run it twice or more. This PR fixes that.
=> Clean up storage after FileBrowserViewTests

.github/workflows/ci.yml, chris_backend/config/settings/common.py, chris_backend/core/serializers.py, chris_backend/core/views.py, chris_backend/feeds/serializers.py, chris_backend/feeds/views.py, chris_backend/filebrowser/serializers.py, chris_backend/filebrowser/views.py, chris_backend/pacsfiles/serializers.py, chris_backend/pacsfiles/views.py, chris_backend/pipelines/serializers.py, chris_backend/pipelines/views.py, chris_backend/plugininstances/serializers.py, chris_backend/plugininstances/spectacular_hooks.py, chris_backend/plugininstances/views.py, chris_backend/plugins/admin.py, chris_backend/plugins/enums.py, chris_backend/plugins/models.py, chris_backend/plugins/serializers.py, chris_backend/userfiles/serializers.py, chris_backend/userfiles/views.py, chris_backend/users/views.py, chris_backend/workflows/serializers.py, chris_backend/workflows/views.py, docker-compose_just.yml, justfile
- Most `get_queryset` overrides need to have an extra two lines of code `if getattr(self, "swagger_fake_view", False): return TheModel.objects.none()`
- Added a class decorator `@core.serializers.file_serializer` which unifies the duplicated code between file serializers which provide the fields `fname`, `fsize`, `file_resource`, `owner_username`, `parent_folder`, and `owner`
=> Fix all spectacular warnings and add OpenAPI spec to release draft

Dockerfile, chris_backend/config/settings/common.py, docker-compose_just.yml, requirements/base.txt, requirements/local.txt, requirements/production.txt
granian is an ASGI server written in Rust. In addition to adding rusty performance and goodness, this also solves a problem with large file uploads that happens with daphne (see https://stackoverflow.com/questions/46986220/daphne-django-file-upload-size-limitations).
I tried uploading an 8GB file and it worked no problem.
=> Replace daphne with granian

chris_backend/config/settings/production.py
Adds the optional environment variables `AUTH_LDAP_USER_SEARCH_FILTER`, `AUTH_LDAP_USER_ATTR_MAP`, `AUTH_LDAP_GROUP_SEARCH_FILTER`, `AUTH_LDAP_USER_FLAGS_BY_GROUP`, and `AUTH_LDAP_MIRROR_GROUPS_EXCEPT`, making LDAP integration much more customizable. In particular, this enables the configuration of workarounds for problems with Authentik's LDAP outpost --> https://github.com/goauthentik/authentik/issues/7522#issuecomment-2525303023
=> Add more optional environment variables for LDAP

chris_backend/core/views.py, chris_backend/filebrowser/views.py, chris_backend/pacsfiles/views.py, chris_backend/pipelines/views.py, chris_backend/userfiles/views.py
- Add Content-Disposition header to file downloads
- Make file download tokens unique within a time interval of a second
=> Add Content-Disposition header to file downloads

chris_backend/core/models.py, chris_backend/core/tests/test_models.py, chris_backend/userfiles/serializers.py, chris_backend/userfiles/tests/test_serializers.py
=> Fix issue that prevented deletion of a folder's descendant folders when the raw storage was a POSIX filesystem

justfile
Prevents the output of `just dev` from being so noisy...
=> Filter out healthcheck endpoint from logs

chris_backend/core/models.py, chris_backend/core/tests/test_models.py, chris_backend/feeds/models.py, chris_backend/feeds/views.py, chris_backend/filebrowser/serializers.py, chris_backend/filebrowser/services.py, chris_backend/userfiles/serializers.py, chris_backend/userfiles/tests/test_serializers.py, chris_backend/workflows/models.py
- Allow new files and folders added to a shared folder to be automatically seen
- Fix feeds page order
=> Allow new files and folders added to a shared folder to be automatically seen

chris_backend/core/celery.py, chris_backend/feeds/models.py, chris_backend/feeds/tests/test_models.py, chris_backend/plugininstances/services/manager.py, chris_backend/plugininstances/tasks.py
1. Make delete requests to pfcon more robust and add periodic task to retry failed requests
2. Share filesystem objects pointed by link files under a feed's folder when the feed is shared
=> Make delete requests to pfcon more robust and add periodic task to retry failed requests

docker-compose.yml
More concise, and also happens to be a workaround for a Podman bug: https://github.com/containers/podman/issues/26519
=> Replace healthcheck CMD with CMD-SHELL

chris_backend/core/celery.py, chris_backend/pacsfiles/tasks.py, chris_backend/plugininstances/models.py, chris_backend/plugininstances/services/manager.py, chris_backend/plugininstances/tasks.py, chris_backend/plugininstances/tests/test_tasks.py, chris_backend/plugininstances/utils.py, chris_backend/plugininstances/views.py
- Add task to cancel plugin instances stuck in 'scheduled' status
- Refactor code to update a plugin instance status
- Optimize some DB queries
Fix #653
=> Add task to cancel plugin instances stuck in 'scheduled' status

chris_backend/config/local_urls.py, chris_backend/config/settings/local.py, chris_backend/config/urls.py, requirements/local.txt
1. remove django-debug-toolbar.
2. remove django-extensions.
3. remove isort.
4. remove pudb.
5. remove https://github.com/msbrogli/rpudb.
6. add comments about the reasons why we need these packags in requirements/local.txt.
=> remove unnecessary pacakges in dev env.
